### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [sheikhhaziq/vibemusic#1]
Thanks for providing your app this way! May I ask what license it falls under? I've looked through the repository but could not find any indicator. Without a license specified it's "all rights reserved", which a.o. might scare potential contributors away. Maybe you simply forgot to declare it?

Should you still be unsure, I'd suggest picking a license approved by OSI/FSF, see e.g. [here](https://spdx.org/licenses/) for a list. The most commonly used ones include Apache-2.0, BSD-3-Clause, MIT, GPL-2.0, GPL-3.0 and AGPL-3.0 (roughly ordered from "lax" to "copy-left"), if that makes your decision easier. Thanks in advance!

PS: Should you "not care at all", there's always the WTFPL :see_no_evil:

**Comment by sheikhhaziq** [comment]
Thanks for raising this issue. We have added license to this repo as you can now see it<a href="https://github.com/sheikhhaziq/vibemusic/blob/main/LICENSE">here</a>. If you want to contribute to this repository, you are welcome.

Once again, thanks for reminding us about it.

**Comment by IzzySoft** [comment]
That was fast – thanks a lot! And while I'm not a dev, my contributions are a little different.

First, I've just added your app to my repo for F-Droid users – it should become [available here](https://apt.izzysoft.de/fdroid/index/apk/com.webyte.vibe_music) around 7 pm UTC with the next sync. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your Readme. Updates will be fetched automatically within 24h of your providing them (by creating a new release and attaching the APK).

Second, if you like I can send the metadata I've set up for your app in my repo in [Fastlane format](https://gitlab.com/-/snippets/1895688) as PR, so you can control how your app is presented (Fastlane would be fetched along with the app updates then).

Third, if you like to take a further step, I can guide you to getting your app listed in the [F-Droid](https://f-droid.org/) repo, which has a bit higher prestige & trust (mine is just the largest 3rd party repo, but still quite popular). Let me know if and when you want this. It's just a recommendation, nothing "mandatory" :wink:

**Comment by sheikhhaziq** [comment]
It'll be helpful if you can send me metadata and also guide me to getting my app listed on <a href="https://f-droid.org/">F-Droid</a>

**Comment by IzzySoft** [comment]
OK, metadata are on their way (PR just linked itself). As Fastlane is one of the things you'd need for a listing there, next steps should only be initiated once that PR was merged, optionally amended by what you feel missing or in need of update and ideally covered by a new tag.

Then the next step would be opening a [Request for Packaging](https://gitlab.com/fdroid/rfp/-/issues/). Fill out the questionnaire to your best knowledge. A little later (usually within an hour) our issuebot will post its "scan results" for our evaluation, and then one of our team¹ should take over (if not, feel free to give me a ping there, I go by the same nick there as here).

Once all engines are green in the RFP, the final phase is a merge request against the fdroiddata repository to get your app listed. Don't worry about that yet, we'll see to it when we arrive at that stage.

Thanks for your interest, and :crossed_fingers: for good progress!

¹ <sub>disclosure: I'm one of the F-Droid maintainers.</sub>
