### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [sheikhhaziq/vibemusic#12]
https://github.com/mondlicht-und-sterne/Translations/blob/main/intl_de.arb

**Comment by sheikhhaziq** [comment]
Make a pull request and I will merge it.

**Comment by mondlicht-und-sterne** [comment]
I do not understand the pullrequest
Well, I can't.
Otherwise someone else will copy it.

**Comment by sheikhhaziq** [comment]
I can add it but you won't be shown as contributer

**Comment by mondlicht-und-sterne** [comment]
I don't mind that.

**Comment by sheikhhaziq** [comment]
German language has been added to repo and will be available with next release.
