### ISSUE TITLE
Chinese text garbled

### ISSUE THREAD

**Issue by aecra** [sheikhhaziq/vibemusic#16]
When I search for Chinese songs, all Chinese-related content is garbled. Can you solve the encoding problem?  

Below are the search results for the song "我相信".

![Screenshot_2023-01-02-17-19-20-921-edit_com.webyte.vibe_music.jpg](https://user-images.githubusercontent.com/34883050/210213236-b4f8de0d-2774-4150-9685-77824527b653.jpg)

**Comment by sheikhhaziq** [comment]
The issue has already been fixed and is now available with new release. You can Download it  [here v0.4.2](https://github.com/sheikhhaziq/vibemusic/releases/tag/0.4.2)
