### ISSUE TITLE
Can you add the Google Signing option and fix it?

### ISSUE THREAD

**Issue by rajinstar** [sheikhhaziq/vibemusic#183]
Dear @sheikhhaziq 

Before this problem, I could sync music from my YouTube music and Gyawun music very easily. When I add music to my YouTube Music playlists from my laptop, it will immediately appear in the Gyawun Music app. And when I add music to the Gyawun Music app playlist, it will immediately appear in the YouTube Music on my desktop. But, after this update, it will not be possible anymore. Can you find any other solution for this problem so that I can experience the previous user experience?

**Comment by sheikhhaziq** [comment]
Google account was removed because google removed support for it. I am currently looking for different way to bring back this feature but it may take some time.

**Comment by rajinstar** [comment]
Thanks brother @sheikhhaziq 🤗

**Comment by rajinstar** [comment]
@sheikhhaziq brother, If you are unable to find any solution for this problem, Then you can add login options both for Windows and Android apps. So, I can create an account and login from both my laptop and phone, and then I can make playlists from my phone and synchronize them from my laptop, or vice versa. In this case, there is no need for a Google account.
