### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by senolfndk** [sheikhhaziq/vibemusic#21]
### Feature description

add to favorites like library trend mp3 download more themes delete search history can you add

**Comment by sheikhhaziq** [comment]
These features are in our [TODO List](https://github.com/sheikhhaziq/vibemusic#features--todo) and will be added soon.

**Comment by senolfndk** [comment]
> Bu özellikleri [YAPILACAKLAR Listemizde](https://github.com/sheikhhaziq/vibemusic#features--todo) ve yakında eklenecektir.

ok
