### ISSUE TITLE
Wrong song displayed when playing

### ISSUE THREAD

**Issue by aecra** [sheikhhaziq/vibemusic#22]
After many verifications, it is found that if the song is frequently switched while playing the song, the song played will be inconsistent with the one displayed on the current page, but at this time the song displayed in the notification bar is consistent with the one played.

**Comment by sheikhhaziq** [comment]
The problem has been fixed ([Here](https://github.com/sheikhhaziq/vibemusic/commit/973987a78b2177464fdb88d90f82bc89e32a0ef0) ) and will be avialable with new release

**Comment by sheikhhaziq** [comment]
you can check it out in [v0.5.1-beta.1 here](https://github.com/sheikhhaziq/vibemusic/releases/tag/v0.5.1-beta.1).
