### ISSUE TITLE
Replay Gain Normalization

### ISSUE THREAD

**Issue by Alliba** [sheikhhaziq/vibemusic#31]
### Feature description

Some songs are louder than others in a playlist. Replay Gain Normalization can be used to make them equally loud.

The variable volume is annoying and some songs aren't even audible unless you manually set the volume right for the song.

**Comment by sheikhhaziq** [comment]
I'll look into it and keep you updated.

**Comment by sheikhhaziq** [comment]
This issue has been solved with [This](https://github.com/sheikhhaziq/vibemusic/releases/tag/v0.6.0-beta.2) release
