### ISSUE TITLE
account in app

### ISSUE THREAD

**Issue by HeroRickyGAMES** [sheikhhaziq/vibemusic#32]
### Feature description

It would be really cool if:
1 the app had an account to make backups
2 as the user consumes music in the app, it will show similar songs like:
2.5: User x likes Rock, and likes classic music, the songs would be arranged with tags and within these tags would have the genre,
As the user consumes, similar music will appear on the home screen, such as rock bands, pop artists, and more.

**Comment by sheikhhaziq** [comment]
For having accounts in app, It might take time. But for backups, we can make it possible by backing up on your phone as a encrypted file which a person can share.

For showing similar content in app, I am looking into it. I might be avialable soon.

**Comment by HeroRickyGAMES** [comment]
Do you use Firebase? just use strings if possible of course.

**Comment by HeroRickyGAMES** [comment]
Using Firebase is much easier.

**Comment by HeroRickyGAMES** [comment]
Thanks for the info

**Comment by sheikhhaziq** [comment]
firebase services are free when users are less but after users increase, we need to pay for it, Still I will think about it.
