### ISSUE TITLE
Play next and Radio button

### ISSUE THREAD

**Issue by GET100PERCENT** [sheikhhaziq/vibemusic#36]
### Feature description

Add play next and Radio button just like official YouTube music.
It's the much required features when streaming musics.

**Comment by sheikhhaziq** [comment]
Both of these features are coming.

**Comment by sheikhhaziq** [comment]
Play next has been added to beta release [here][https://github.com/sheikhhaziq/vibemusic/releases/tag/v0.6.0-beta.1) and radio option will be added soon

**Comment by sheikhhaziq** [comment]
Play next has been added to beta release [here](https://github.com/sheikhhaziq/vibemusic/releases/tag/v0.6.0-beta.1) and radio option will be added soon
