### ISSUE TITLE
Russian language support (Cyrillic script)

### ISSUE THREAD

**Issue by Alliba** [sheikhhaziq/vibemusic#4]
If the Russian language (Cyrillic script) is not supported.

See screenshot.

![Screenshot_20221214-214635](https://user-images.githubusercontent.com/103368536/207711157-9482777a-3fce-4e4d-b386-c40771feac7b.jpg)

**Comment by sheikhhaziq** [comment]
I'm currently working on multilanguage support. Russian will be added soon as well

**Comment by sheikhhaziq** [comment]
Russian support has been added in **Vibe Music**. it may not apply to data as it is being fetched form ytmusicapi.

**Comment by Alliba** [comment]
> Russian support has been added in **Vibe Music**. it may not apply to data as it is being fetched form ytmusicapi.

The error persists.
![Screenshot_20221231-164733](https://user-images.githubusercontent.com/103368536/210148705-af48a07f-773d-41a7-a564-9c2beef4d6d2.jpg)

**Comment by sheikhhaziq** [comment]
As I said inapp support has been added. The problem is with the data fetched. I am currently working on it.

**Comment by Alliba** [comment]
> As I said inapp support has been added. The problem is with the data fetched. I am currently working on it.

Okay, thanks.

**Comment by sheikhhaziq** [comment]
![IMG_20230101_103402](https://user-images.githubusercontent.com/41983383/210161713-5a3e92be-8029-4327-9b7f-a21f5b0ed705.jpg)
The fix has been added to repo and will be add to the next release

**Comment by Alliba** [comment]
> ![IMG_20230101_103402](https://user-images.githubusercontent.com/41983383/210161713-5a3e92be-8029-4327-9b7f-a21f5b0ed705.jpg) The fix has been added to repo and will be added to the next release

👍
