### ISSUE TITLE
Improvement in notification area 

### ISSUE THREAD

**Issue by anujithpp** [sheikhhaziq/vibemusic#44]
![Screenshot_2023-01-13-20-22-10-07_844ec63a5ee7251970ee812a79420e73.jpg](https://user-images.githubusercontent.com/106502495/212349492-7133c9be-e288-4302-b307-e94cd053fb68.jpg)
This is just boring
![Screenshot_2023-01-13-20-22-30-87_67d7f8591eff9881972c1169b8bca2d8.jpg](https://user-images.githubusercontent.com/106502495/212349591-a8e15063-26c6-4cba-9644-e9553d95eba4.jpg)
Something like this will look good

**Comment by sheikhhaziq** [comment]
Notification area will be updated soon
