### ISSUE TITLE
song transition

### ISSUE THREAD

**Issue by senolfndk** [sheikhhaziq/vibemusic#48]
### Steps to reproduce the bug

Can you slow down the song transition?

### Expected behavior

Can you slow down the song transition?

### Actual behavior

Can you slow down the song transition?

### Screenshots/Screen recordings

Can you slow down the song transition?

### Logs

Can you slow down the song transition?

### Vibe Music version

0.6.1

### Android version

android 12

**Comment by sheikhhaziq** [comment]
What do you mean by song transition

**Comment by senolfndk** [comment]
song skip slow can you speed it up

**Comment by sheikhhaziq** [comment]
You mean when you go to the next song

**Comment by senolfndk** [comment]
> Bir sonraki şarkıya gittiğinde demek istiyorsun

yes

**Comment by sheikhhaziq** [comment]
> 

I'll look into it

**Comment by senolfndk** [comment]
> > 
> 
> araştıracağım

ok

**Comment by sheikhhaziq** [comment]
The issue has been solved in last commit.
