### ISSUE TITLE
delete search history

### ISSUE THREAD

**Issue by senolfndk** [sheikhhaziq/vibemusic#49]
### Feature description

![Screenshot_20230114-170305_YMusic](https://user-images.githubusercontent.com/52818836/212481881-8af357b5-0ac2-4aac-9b65-5124c1bb4b7d.jpg)

**Comment by sheikhhaziq** [comment]
Long press on search history item to delete it

**Comment by senolfndk** [comment]
I know can it be like in the picture

**Comment by senolfndk** [comment]
I know can it be like in the picture

**Comment by sheikhhaziq** [comment]
I don't get it.

**Comment by senolfndk** [comment]
> anlamadım



> anlamamış

I'm sorry, excuse me

**Comment by sheikhhaziq** [comment]
If you option to clear all history together, that's coming in next update

**Comment by senolfndk** [comment]
I know

**Comment by senolfndk** [comment]
> Tüm geçmişi birlikte temizleme seçeneği istiyorsanız, bu bir sonraki güncellemede geliyor

can it be like in the picture

**Comment by sheikhhaziq** [comment]
Do you mean cross option

**Comment by senolfndk** [comment]
https://user-images.githubusercontent.com/52818836/212482619-fb69d81c-0b7b-481f-a389-206f0ad18b92.mp4

**Comment by sheikhhaziq** [comment]
You want cross icon to delete history

**Comment by senolfndk** [comment]
yes

**Comment by sheikhhaziq** [comment]
I can add that
