### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by senolfndk** [sheikhhaziq/vibemusic#50]
### Feature description

some features
![Screenshot_20230114-221501](https://user-images.githubusercontent.com/52818836/212492334-04cc9ec0-fccd-4a66-9b35-b0439e343fa6.jpg)

**Comment by sheikhhaziq** [comment]
All of these features are coming 🥳

**Comment by senolfndk** [comment]
thanks you are great 😉

**Comment by Inspiredshadow** [comment]
> All of these features are coming 🥳

When will be the new release?
