### ISSUE TITLE
Language pt-BR and fix latin ascent

### ISSUE THREAD

**Issue by BoxerT1** [sheikhhaziq/vibemusic#6]
Hi, can i help translate to portuguese brazil?
About ascent fix it's about this words above:

Áãâèéêçíôõó... Etc
![IMG_20221222_002606](https://user-images.githubusercontent.com/81737635/209049110-ffa63e80-cd27-4a3b-af18-e72981f55605.jpg)

H5 from Brazil

**Comment by sheikhhaziq** [comment]
You are welcome to help. You can contribute by creating a pull request.

**Comment by sheikhhaziq** [comment]
Portuguese has been added in new release. Changes may not reflect in data as it is being fetched from ytmusicapi.
