### ISSUE TITLE
Screen revolution 

### ISSUE THREAD

**Issue by owencz1998** [sheikhhaziq/vibemusic#7]
Doesn't fit the z fold 3 front screen :)

**Comment by sheikhhaziq** [comment]
can you share the screenshot

**Comment by owencz1998** [comment]
![Screenshot_20221230_193327.jpg](https://user-images.githubusercontent.com/96526481/210106146-1e133115-ab3d-480e-81fb-692ef6ecb6fd.jpg)

**Comment by owencz1998** [comment]
Only the bottom part mate

**Comment by sheikhhaziq** [comment]
You mean the controls are overflowing... I will fix them as soon as possible.

**Comment by sheikhhaziq** [comment]
we have added the fix to this overflow problem. you can check it out [here](https://github.com/sheikhhaziq/vibemusic/releases/tag/v0.3.1), and provide us with your feedback.

**Comment by owencz1998** [comment]
Thank u so much works grate 🤟
