### ISSUE TITLE
versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [sheikhhaziq/vibemusic#8]
I just noticed that your second release still identifies with `versionCode: 1`, which makes auto-updates impossible (as Android uses `versionCode` to tell versions apart). Strangely, your [`pubspec.yaml`](https://github.com/sheikhhaziq/vibemusic/tree/v0.2.1) even states a `versionCode: 0` (`version: 0.2.1+0`), so I don't know where you set it.

Can you please take care to increasse `versionCode` properly with future releases? Thanks in advance!

**Comment by sheikhhaziq** [comment]
The `versionCode` has been updated to 2.

**Comment by IzzySoft** [comment]
Thanks! Please keep increasing it with each future release :smiley:
