### ISSUE TITLE
No longer functional. Dev still active? 

### ISSUE THREAD

**Issue by n3rdcub** [sheikhhaziq/vibemusic#84]
### Steps to reproduce the bug

Steps to reproduce;
1. Open app
2. Select any song
3. Try downloading

### Expected behavior

When you download a song it should download as intended

### Actual behavior

It keeps taking you to app settings and never downloads.
There's no storage permission listed lol

### Vibe Music version

Latest

### Android version

13

### Additional information

Running GrapheneOS

**Comment by n3rdcub** [comment]
Hey don't worry about it I'm sure you're super busy doing... Something. I fixed it myself

You didn't include storage permission in 0.9.1 but it exists in 9.0 beta.

Not sure how you remove a permission with an update and a critical one at that but you should pull 0.9.1

**Comment by sheikhhaziq** [comment]
Did you mean permission is removed in androidmanifest.xml

**Comment by n3rdcub** [comment]
I'm not a dev but sure maybe? There's simply no storage permission in current stable and most recent beta. Downloading songs either doesn't work or is not present. 

HOWEVER, in 9.0.0 beta there IS a download button that IS functional and working as intended. 9.0.1 does NOT work as intended due to missing permission

**Comment by DarkCrypt** [comment]
I looked at both of these beta builds (v0.9.0 & v0.9.1) and they have the exact same permissions. There were no permission changes in changelog between versions.

Neither version worked for me on Android 13 for download function.
___
@sheikhhaziq 

v0.9.2 beta download function works great. Nice work! 👍
